language: cpp
python: "3.7"
sudo: required
dist: bionic
compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - pip install conan --user
  - conan user

before_script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake ..
  
script: 
  - make
  - ctest
