language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc

install:
  - pip install conan
  - conan user

before_script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake ..
  
script: 
  - make
  - ctest
