image:
  - Visual Studio 2017
platform:
  - x64
clone_folder: c:\projects\source

install:
- cmd: >-
    echo "Downloading conan..."
    
    set PATH=%PATH%;%PYTHON%/Scripts/
    
    pip.exe install conan
    
    conan profile new default --detect
    
    conan --version

build_script:
- cmd: >-
    mkdir build
  
    cd build
    
    conan install .. --build
  
    cmake c:\projects\source -G "Visual Studio 15"
  
    cmake --build . --config "Debug"
