image:
  - Visual Studio 2017
clone_folder: c:\projects\source

install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version

build_script:
- cmd: >-
    mkdir build
  
    cd build
    
    conan install .. --build
  
    cmake c:\projects\source -G "Visual Studio 15"
  
    cmake --build . --config "Debug"
