image:
  - Visual Studio 2017
platform:
  - x64
clone_folder: c:\projects\source

install:
- cmd: >-
    echo "Downloading conan..."
    
    set PATH=%PATH%;%PYTHON%/Scripts/
    
    pip.exe install conan
    
    conan profile new default --detect
    
    conan --version

build_script:
- cmd: >-
    mkdir build
  
    cd build
    
    conan install .. -o gtest:shared=false
  
    cmake c:\projects\source -DBUILD_TEST=TRUE -G "Visual Studio 15" -DCMAKE_GENERATOR_PLATFORM=x64
  
    cmake --build . --config "Debug"

test_script:
- cmd: >-
    ctest . -C "Debug"
