image:
  - Visual Studio 2017
  
platform:
  - x64
  
clone_folder: c:\projects\source

install:
- cmd: >-
    echo "Downloading conan..."
    
    set PATH=%PATH%;%PYTHON%/Scripts/
    
    pip.exe install conan
    
    conan profile new default --detect
    
    conan --version

configuration:
  - Release

build_script:
- mkdir build
- cd build
- conan install .. -o gtest:shared=True
- cmake c:\projects\source -DBUILD_TEST=TRUE -G "Visual Studio 15" -DCMAKE_GENERATOR_PLATFORM=x64
- cmake --build . --config %CONFIGURATION%
    
test_script:
- cmd: ctest . -C %CONFIGURATION% --timeout 60 --output-on-failure


